handlers:
- url: /favicon.ico
  static_path: favicon.ico
- url: /static/footer.css
  static_path: static/footer.css
  url: /static/main.css
  static_path: static/main.css
  url: /static/main.js
  static_path: static/main.js
  url: /static/jquery.js
  static_path: static/jquery.js